name: "miniconda arm64 ubuntu CI workflow"


on:
  push:
    branches: [ main ]
  schedule:
      - cron:  '0 0 1 * *' ##execution of a task in the first minute of the month      


jobs:

     

  ubuntu-1604-miniconda-arm64v8-job:
    name: "miniconda arm64v8 ubuntu-16.04"
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: hostnamectl status  
    - name: "deploy miniconda arm64v8"
      run: make deploy-miniconda-arm64 


  ubuntu-1804-conda-job:
    name: "ubuntu-18.04 conda latest"
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: hostnamectl status  
    - name: "deploy miniconda arm64v8"
      run: make deploy-miniconda-arm64        

  ubuntu-2004-conda-job:
    name: "ubuntu-20.04 conda latest"
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: hostnamectl status 
    - name: "deploy miniconda arm64v8"
      run: make deploy-miniconda-arm64 

  ubuntu-latest-conda-job:
    name: "ubuntu-latest conda latest"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: hostnamectl status  
    - name: "deploy miniconda arm64v8"
      run: make deploy-miniconda-arm64       